In [1]:
import torch as tr
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
print(tr.__version__)
print(np.__version__)
print(pd.__version__)
print(plt.matplotlib.__version__)

2.12.1+cu132
2.4.6
3.0.3
3.11.0


In [2]:
#scaler 
scaler = tr.tensor(8) 
print(scaler)
print(type(scaler))
scaler.item()  #returns the tensor back to integer
print(scaler.item())
print(type(scaler.item()))

tensor(8)
<class 'torch.Tensor'>
8
<class 'int'>


In [3]:
#vector
vector = tr.tensor([4,5])
print(vector)

# vector.ndim
print(vector.ndim)
vector.shape




tensor([4, 5])
1


torch.Size([2])

In [4]:
#matrix
matrix = tr.tensor([[1,2], [3,4]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[1, 2],
        [3, 4]])
2
torch.Size([2, 2])


In [5]:
#3d tensor
tensor = tr.tensor([[[1,2,3], [3,4,5], [2, 4, 7]]])
print(tensor)
print(tensor.ndim)
print(tensor.shape)
tensor[0][0][0]

tensor([[[1, 2, 3],
         [3, 4, 5],
         [2, 4, 7]]])
3
torch.Size([1, 3, 3])


tensor(1)

In [6]:
##Random Tensors
np.random.seed(42)
random_tensor = tr.rand(2, 3, 4, 5)
print(random_tensor)

tensor([[[[0.0273, 0.5089, 0.2069, 0.4135, 0.9671],
          [0.6469, 0.3279, 0.0326, 0.0657, 0.0144],
          [0.0027, 0.2830, 0.9496, 0.2201, 0.6835],
          [0.7543, 0.6181, 0.2772, 0.4858, 0.5015]],

         [[0.5175, 0.5753, 0.2903, 0.0725, 0.2721],
          [0.7961, 0.1326, 0.7147, 0.6419, 0.4131],
          [0.0524, 0.7501, 0.4842, 0.2298, 0.2469],
          [0.3475, 0.4414, 0.9038, 0.5024, 0.2118]],

         [[0.2390, 0.5123, 0.9123, 0.7942, 0.1969],
          [0.4415, 0.2987, 0.2912, 0.6582, 0.6099],
          [0.3253, 0.8779, 0.4832, 0.6970, 0.0949],
          [0.6680, 0.9034, 0.7883, 0.3050, 0.3679]]],


        [[[0.5240, 0.5653, 0.6457, 0.0763, 0.2690],
          [0.1297, 0.6542, 0.4471, 0.8097, 0.2762],
          [0.4790, 0.7412, 0.3883, 0.0993, 0.3852],
          [0.8065, 0.5916, 0.5735, 0.2242, 0.5520]],

         [[0.9430, 0.1947, 0.7992, 0.5448, 0.7965],
          [0.7002, 0.1782, 0.1922, 0.8900, 0.0394],
          [0.0571, 0.1854, 0.6953, 0.1857, 0.1041],
  

In [7]:
## random tensor with similar shape

random_image_shape = tr.rand((224, 224, 3))
random_image_shape.size, random_image_shape.ndim, random_image_shape.shape

(<function Tensor.size>, 3, torch.Size([224, 224, 3]))

In [8]:
##zeros and ones
tensor_zero = tr.zeros(3, 4)
print(tensor_zero)

tensor_ones = tr.ones(3, 4)
print(tensor_ones)
tensor_ones.dtype, tensor_ones.device, tensor_ones.shape
# tensor_zero.dtype, tensor_zero.device, tensor_zero.shape

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


(torch.float32, device(type='cpu'), torch.Size([3, 4]))

In [9]:
### creating  a tensor of range

tensor_range = tr.arange(1, 500, 66)
print(tensor_range)
tensor_range.dtype, tensor_range.device, tensor_range.shape
tensor_range.ndim

ten_zeros = tr.zeros_like(input= tensor_range)
ten_zeros

tensor([  1,  67, 133, 199, 265, 331, 397, 463])


tensor([0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
tensor_float = tr.tensor([1.0, 2.0 , 3.0], dtype=tr.int32, device=None, requires_grad=False)
tensor_float, tensor_float.dtype, tensor_float.device, tensor_float.requires_grad

(tensor([1, 2, 3], dtype=torch.int32), torch.int32, device(type='cpu'), False)

In [11]:
print('{0:.2%}'.format(2/5))

40.00%


In [12]:
float_32_tensor = tensor_float.type(tr.float32)
print(type(float_32_tensor))

<class 'torch.Tensor'>


In [13]:
listq = [1, 2, 3, 4, 5]
for i in listq:
    listq.remove(i)

print(listq)

[2, 4]


In [14]:
tensor_mul = float_32_tensor *  tensor_float
print(tensor_mul)

tensor([1., 4., 9.])


In [15]:
int_tensor = tr.tensor([1, 2, 3], dtype=tr.float32)
print(float_32_tensor * int_tensor)
print(int_tensor.device)

tensor([1., 4., 9.])
cpu


In [16]:
# int_tensor * 12
# int_tensor + 12
# int_tensor - 12
# int_tensor / 12
%%time
tensor_mat = tr.tensor([[1, 2], [3, 4]])
tensor_mat2 = tr.tensor([[5, 6], [7, 8]])
# print(tensor_mat @ tensor_mat2)
# print(tensor_mat.matmul(tensor_mat2))

UsageError: Line magic function `%%time` not found.


In [17]:
a = tr.rand(3, 2)
print(a)
b = tr.rand(2, 7)
print(b)
print(a @ b)

tensor([[0.2304, 0.4923],
        [0.1872, 0.9290],
        [0.7665, 0.7795]])
tensor([[0.7260, 0.9101, 0.2666, 0.9366, 0.4848, 0.1887, 0.7252],
        [0.6719, 0.0287, 0.9771, 0.8500, 0.5174, 0.4369, 0.7617]])
tensor([[0.4980, 0.2238, 0.5425, 0.6342, 0.3664, 0.2585, 0.5420],
        [0.7601, 0.1970, 0.9577, 0.9650, 0.5714, 0.4412, 0.8434],
        [1.0802, 0.7199, 0.9660, 1.3804, 0.7749, 0.4852, 1.1495]])


In [18]:
tensor_a = tr.tensor([[1, 2], [3, 4]])
tensor_b = tr.tensor([[5, 6], [7, 8]])  
print(tensor_a @ tensor_b)
print(tensor_a.mm(tensor_b))

tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


In [19]:
tens = tr.tensor([[1, 2], [3, 4], [5, 6]])
tens_a = tr.tensor([[1, 2], [3, 4]])
print(tens_a)
tens
print(tens_a @ tens.T)

tensor([[1, 2],
        [3, 4]])
tensor([[ 5, 11, 17],
        [11, 25, 39]])


In [20]:
x = tr.arange(1, 100, 10)
print(x)
print(min(x))

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
tensor(1)


In [21]:
print(tr.mean(x.type(tr.float32)))

tensor(46.)


In [29]:
##reshape, sqeeze, unsqueeze, 
a = tr.arange(1., 10., 1.)
a.shape
a_reshape = a.reshape(3, 3)
print(a_reshape)
a_reshape.shape

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


torch.Size([3, 3])

In [31]:
##view
s = a.view(3, 3)
s
r = s[:, 0] = 6
print(s, a)

tensor([[6., 2., 3.],
        [6., 5., 6.],
        [6., 8., 9.]]) tensor([6., 2., 3., 6., 5., 6., 6., 8., 9.])


In [34]:
##stack tensor on top

s_stack = tr.stack([s, s, s], dim=2)
print(s_stack)

tensor([[[6., 6., 6.],
         [2., 2., 2.],
         [3., 3., 3.]],

        [[6., 6., 6.],
         [5., 5., 5.],
         [6., 6., 6.]],

        [[6., 6., 6.],
         [8., 8., 8.],
         [9., 9., 9.]]])


In [45]:
##squeeze and unsqueeze
x = tr.tensor([1,2,3,4,5,6,7])
print(x)
print(x.shape)
f = tr.squeeze(x)
print(f)
print(f.shape)
h = tr.unsqueeze(f, dim=0)
print(h)
print(h.shape)

tensor([1, 2, 3, 4, 5, 6, 7])
torch.Size([7])
tensor([1, 2, 3, 4, 5, 6, 7])
torch.Size([7])
tensor([[1, 2, 3, 4, 5, 6, 7]])
torch.Size([1, 7])


In [ ]:
##permute

x = tr.rand(224, 224, 3)
print(x)
x_permuted = tr.permute(x, (2, 0, 1))
print(x_permuted)
print(x_permuted.shape)



In [78]:
x = tr.arange(1, 28, 1)
x_r = x.reshape(3, 3, 3)
print(x_r)

x_r[0,:,2]


tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])


tensor([3, 6, 9])

## Python numpy and Tensors


In [87]:
import numpy as np
arr = np.arange(1, 8)
tensor = tr.from_numpy(arr)
arr = arr + 1
arr, tensor
print(type(tensor))
tensor.dtype

<class 'torch.Tensor'>


torch.int64

In [101]:
## Reproducbility 

rand_seed = 42
tr.manual_seed(rand_seed)
x = tr.rand(3, 3)
tr.manual_seed(rand_seed)
y = tr.rand(3,3)
print(x == y)


tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
